name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 65002
          script: |
            cd /home/u386335356/domains/adsensedesigns.com/public_html/spedition-laravel
            
            # Code pull 
            git pull origin main
            
            # Dependencies install/update karein
            composer install --no-dev --optimize-autoloader
            
            # Cache clear aur optimize karein
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            
            php artisan storage:link